# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'RUM Mobile Demo App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RUM Mobile Demo App

	pod 'Alamofire'
	#pod 'Alamofire', '~> 4.7'
	pod 'AlamofireObjectMapper', '~> 5.2'
  pod 'IQKeyboardManager'

end
